server:
  port: 8086

spring:
  application:
    name: data-service-poc
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    open-in-view: true
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/sport_data?createDatabaseIfNotExist=false
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
management:
  endpoints:
    web:
      exposure:
        include: "*"

springdoc:
  swagger-ui:
    path: "/docs"
